<?php

// namespace Drupal\virtual_edit_link_field;


/**
 * @file
 * Contains virtual_edit_link_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_help().
 */
function virtual_edit_link_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the virtual_edit_link_field module.
    case 'help.page.virtual_edit_link_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Creates a virtual edit link field. This contains a virtual link that is useful for linking from a decoupled system or app.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_base_field_info_alter().
 */
function virtual_edit_link_field_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {

  if ($entity_type->id() === "node" ) {
    $fields['editLink'] = BaseFieldDefinition::create('string')
      ->setName('Virtual Edit Link Field')
      ->setLabel(t('Edit Link'))
      ->setTargetEntityTypeId('node') // required for content translation
      ->setComputed(TRUE)
      ->setClass('\Drupal\virtual_edit_link_field\ComputedField')
      ->setReadOnly(TRUE)
      ->setRevisionable(TRUE)
      ->setTranslatable(TRUE);
  }

}
